### ISSUE TITLE
feature: optionally limit exec commands to specific allow-listed (or deny-listed) commands

### ISSUE THREAD

**Issue by diranged** [diranged/oz#51]
We should be able to block `kubectl exec <pod> -- <command ...>` calls where `<command>` either matches or does not match a particular list. This would would allow operators to allow-list or deny-list certain commands, providing more protection within the container for what is allowed.

Eg.
```yaml
apiVersion: crds.wizardofoz.co
kind: PodAccessTemplate
metadata:
  name: ...
spec:
  ...
  execAccessConfig:
    allowedCommands:
      - /opt/app/manage.py
      - /opt/app/debug.py
```

We receive the command data through the `PodExecOptions{}` resource on the webhook...

```json
{
  "uid": "7960530b-e935-4e61-aa05-205eaa5aebe5",
  "kind": {
    "group": "",
    "version": "v1",
    "kind": "PodExecOptions"
  },
  "resource": {
    "group": "",
    "version": "v1",
    "resource": "pods"
  },
  "subResource": "exec",
  "requestKind": {
    "group": "",
    "version": "v1",
    "kind": "PodExecOptions"
  },
  "requestResource": {
    "group": "",
    "version": "v1",
    "resource": "pods"
  },
  "requestSubResource": "exec",
  "name": "example-7c7767bc7d-864tt",
  "namespace": "oz-system",
  "operation": "CONNECT",
  "userInfo": {
    "username": "kubernetes-admin",
    "groups": [
      "system:masters",
      "system:authenticated"
    ]
  },
  "object": {
    "kind": "PodExecOptions",
    "apiVersion": "v1",
    "stdin": true,
    "stdout": true,
    "tty": true,
    "container": "nginx",
    "command": [
      "uptime"
    ]
  },
  "oldObject": null,
  "dryRun": false,
  "options": null
}
```
